services:
  - type: web
    name: ai-coach-bot
    runtime: python
    buildCommand: ""
    startCommand: "python coach.py"
    envVars:
      - key: GROQ_API_KEY
        value: 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
      - key: GUPSHUP_API_KEY
        value: 3gie2jrpmj6zb8n9gz4sulh5fcd98xsh
